# Default configuration for training the hierarchical reasoning model with ACT

# architecture config 
[architecture]
vocab_size = 100
seq_length = 1024

[architecture.transformer_block]
embedding_dim = 512
num_heads = 8
is_casual = false
expansion = 4.0
rms_norm_eps = 1e-5

[architecture.token_embeddings]
num_embeddings = 100
embedding_dim = 512
init_std = 0.02

[architecture.pos_embeddings]
num_embeddings = 1024
embedding_dim = 512
init_std = 0.02

[architecture.reasoning_h]
layers = 4
cycles = 2

[architecture.reasoning_l]
layers = 4
cycles = 2

# ACT (Adaptive Computation Time) Controller config
[act_controller]
exploration_prob = 0.1
halt_max_steps = 10

# Loss 
[loss]
function = "stablemax_cross_entropy"

# Random seed for reproducibility
[data]
seed = 42
path = "data/maze-30x30-hard-1k"

# Embeddings config
[embeddings]
optimizer.lr = 1.0e-2
optimizer.weight_decay = 0.1

# Optimizer config
[optimizer]
lr = 1.0e-4
weight_decay = 0.1
betas = [0.9, 0.95]

# Scheduler config
[scheduler]
warmup_steps = 2000
min_ratio = 1.0
